# Generated by Django 5.0 on 2023-12-19 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_trpsigns_date_alter_trpsigns_name_of_sign_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VictoryOrPrizePlaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_include', models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], verbose_name='Мероприятие включено в официальные календари организаций, занимающихся проведением студенческих соревнований?')),
                ('fefu_team', models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], verbose_name='Принадлежность к сборной ДВФУ?')),
                ('place', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], verbose_name='Достижение')),
                ('status_of_the_event', models.CharField(choices=[('Внутривузовский', 'Внутривузовский'), ('Региональный', 'Региональный'), ('Межрегиональный(ДВФО)', 'Межрегиональный(ДВФО)'), ('Всеросийский', 'Всеросийский'), ('Международный', 'Международный')], max_length=255, verbose_name='Уровень(статус) мероприятия')),
                ('name', models.CharField(max_length=255)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
                ('type_of_achievement', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.typesofachievements', verbose_name='Тип достижения')),
            ],
            options={
                'verbose_name': 'Сопровождения одного из направлений мероприятия ДВФУ(техническая группа, ведущие, фото-/видео- съемка)',
                'verbose_name_plural': 'Сопровождения одного из направлений мероприятия ДВФУ(техническая группа, ведущие, фото-/видео- съемка)',
            },
        ),
    ]
