# Generated by Django 5.0 on 2023-12-19 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_victoryorprizeplaces'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='victoryorprizeplaces',
            options={'verbose_name': 'Сопровождения одного из направлений мероприятия ДВФУ', 'verbose_name_plural': 'Сопровождения одного из направлений мероприятия ДВФУ'},
        ),
    ]
