# Generated by Django 5.0 on 2023-12-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_victoryorprizeplaces_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='victoryorprizeplaces',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название спортивного мероприятия'),
        ),
    ]
