# Generated by Django 5.0 on 2023-12-19 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_victoryorprizeplaces_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='victoryorprizeplaces',
            options={'verbose_name': 'Победы/призовые места в спортивных мероприятиях', 'verbose_name_plural': 'Победы/призовые места в спортивных мероприятиях'},
        ),
    ]
