# Generated by Django 5.0 on 2023-12-19 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_victoryorprizeplaces_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportsOfDirections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_to_the_event', models.URLField(verbose_name='Ссылка на мероприятие(с указанием результата выступления)')),
                ('venue', models.CharField(max_length=255, verbose_name='Место проведения/площадка')),
                ('conducting_organization', models.CharField(max_length=255, verbose_name='Проводящая организация')),
                ('date_of_the_event_the_beginning', models.DateField(verbose_name='Дата проведения - начало')),
                ('date_of_the_event_the_ending', models.DateField(verbose_name='Дата проведения - окончание')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
                ('type_of_achievement', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.typesofachievements', verbose_name='Тип достижения')),
            ],
            options={
                'verbose_name': 'Сопровождения одного из направлений мероприятия ДВФУ',
                'verbose_name_plural': 'Сопровождения одного из направлений мероприятия ДВФУ',
            },
        ),
    ]
