# Generated by Django 5.0 on 2023-12-19 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_supportsofdirections'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SportsCategoryOrTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_the_categories_or_titles', models.CharField(choices=[('Мастер спорта международного класса', 'Мастер спорта международного класса'), ('Мастер спорта России', 'Мастер спорта России'), ('Гроссмейстер России', 'Гроссмейстер России'), ('Кандидат в мастера спорта', 'Кандидат в мастера спорта')], max_length=255, verbose_name='Наименование разряда/звания')),
                ('type_of_sport', models.CharField(max_length=255, verbose_name='Вид спорта')),
                ('date_of_assignment', models.DateField(verbose_name='Дата присвоения')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Спортивные разряды/звания',
                'verbose_name_plural': 'Спортивные разряды/звания',
            },
        ),
    ]
